### ISSUE TITLE
Muscle 5.1 breaks the excution of `artic minion`

### ISSUE THREAD

**Issue by pdp10** [artic-network/fieldbioinformatics#105] opened 2022-02-14 12:14 UTC
As you do not pin the version of your dependency package `muscle` to 3.8, the higher version 5.1 is now chosen by conda.

The 5.1 version has a different command set and your code now raises the following error: 
```
Running: muscle -in 20200311_1427_X1_FAK72834_a3787181_barcode07.muscle.in.fasta -out 20200311_1427_X1_FAK72834_a3787181_barcode07.muscle.out.fasta

Invalid command line
Unknown option in
```

**Comment by thomasbtf** [comment] 2022-02-15 07:44
Having the same problem here. This also affects ARTIC wrappers such as [ncov2019-artic-nf](https://github.com/connor-lab/ncov2019-artic-nf).

**Comment by tavareshugo** [comment] 2022-02-21 19:45
Having same issue here using the [ncov2019-artic-nf](https://github.com/connor-lab/ncov2019-artic-nf). 

Although, from the [environment.yml](https://github.com/artic-network/fieldbioinformatics/blob/23a8460f5b881c5b2712c0381e0ec4dc84d38359/environment.yml#L18) it does seem that the correct version is specified. 

I think the problem might be with the [conda recipe](https://github.com/bioconda/bioconda-recipes/blob/01b318ec1b9ccb1594749805b3f04dcbf45d3495/recipes/artic/meta.yaml#L46), which specifies version >=3.8.

So, I guess we need to open an issue/pull request in there instead?

**Comment by thomasbtf** [comment] 2022-02-21 19:49
Did that: https://github.com/bioconda/bioconda-recipes/pull/33172

However, the tests didn't pass and I haven't had time to take a closer look.

If anyone can lend a hand, please feel free to do so!

**Comment by tavareshugo** [comment] 2022-02-21 20:46
I'm not really experienced with conda-recipes, but I can't really understand what the problem is from [the logs](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=12025&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=633). From line 633, it seems like the installation of the environment fails (or was killed for some reason), which I guess is then triggering the error later when it tries to activate that environment and run the `artic`-specific tests?

My hack for the [ncov2019-artic-nf](https://github.com/connor-lab/ncov2019-artic-nf) in particular was to change the [nanopore environment.yml](https://github.com/connor-lab/ncov2019-artic-nf/blob/master/environments/nanopore/environment.yml) to include `- muscle=3.8` in the dependencies list.

**Comment by BioWilko** [comment] 2022-02-23 17:20
The recipe for v1.2.2 has now been merged on the bioconda recipes repo, it should take about 30 mins to propagate.

**Closed by BioWilko** 2022-02-23 17:20 UTC
